FROM node:18.9-alpine

RUN npm install -g pnpm@8

ENV NODE_ENV development
ENV USE_POLLING false
ENV CHOKIDAR_USEPOLLING ${USE_POLLING}

WORKDIR /usr/src/app

COPY package*.json pnpm-lock.yaml* ./

RUN pnpm i

COPY . .

EXPOSE 5050

EXPOSE 24678

CMD pnpm run dev
