version: '1'

services:
  db:
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
    secrets:
      - POSTGRES_PASSWORD
    image: postgres:15.3-alpine
    ports:
      - "5432:5432"
      
  api:
    restart: on-failure
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile.dev
      args:
        BINARY: backend_api
    environment:
      ROCKET_ENV: development
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
    ports:
      - "8000:8000"
    volumes:
      - cargo-cache:/root/.cargo

  filewatcher:
    restart: on-failure
    depends_on:
      - db
    build:
      dockerfile: Dockerfile.dev
      context: .
      args:
        BINARY: filewatcher
    environment:
      ROCKET_ENV: development
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
    ports:
      - "8001:8001"
    volumes:
      - .watchdir:/home/.watchdir

volumes:
  cargo-cache: {}

secrets:
  POSTGRES_PASSWORD:
    file: ./secrets/POSTGRES_PASSWORD
