name: build-webapp
run-name: ${{ github.actor }} is building webapp container images
on:
  push:
    branches:
      - main

jobs:
  webapp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create .env file
        working-directory: frontend
        run: |
          touch .env
          echo PUBLIC_SERVER_URL="https://api.hqproperties.ca" >> .env
          cat .env

      - name: Build and push webapp image
        uses: docker/build-push-action@v4
        with:
          context: "./frontend"
          file: Dockerfile.prod
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hq-webapp:latest

  nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push nginx image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:frontend/nginx/prod"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hq-nginx:latest
          