name: lint-webapp
run-name: ${{ github.actor }} is testing hq-properties webapp
on:
  push:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install pnpm global package manager
        uses: pnpm/action-setup@v2
        with:
          version: '8.x'

      - name: Create .env file
        working-directory: frontend
        run: |
          touch .env
          echo PUBLIC_SERVER_URL="https://api.hqproperties.ca" >> .env
          echo PUBLIC_ANALYTICS_ID="UA-XXXXX-X" >> .env
          cat .env

      - name: Create dummy nginx key and cert
        working-directory: frontend/nginx
        run: |
          touch local.cert.pem
          touch local.key.pem

      - run: pnpm install --silent
      - run: pnpm check
      - run: pnpm lint
      - run: pnpm check-format
  

